// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/core_dsp.dart';
import 'api/core_metadata.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiCoreDspInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -998955986;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_djstudio_player',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<double> crateApiCoreDspAutoDetectAndInjectBpm({
    required String inputPath,
  });

  Future<bool> crateApiCoreDspCheckWatermark({required String inputPath});

  Future<bool> crateApiCoreDspClearWatermark({required String inputPath});

  Future<Uint8List> crateApiCoreDspDecodeMonoPcm({
    required String inputPath,
    required int startSecs,
    required int lengthSecs,
    required int targetRate,
  });

  Future<bool> crateApiCoreDspEncodeToMp3({
    required String inputPath,
    required String outputPath,
    required int bitrateKbps,
  });

  Future<BigInt> crateApiCoreDspExactDurationMs({required String inputPath});

  Future<BigInt> crateApiCoreDspGetAudioDurationMs({required String inputPath});

  Future<void> crateApiCoreDspInitApp();

  Future<bool> crateApiCoreDspInjectWatermark({required String inputPath});

  Future<bool> crateApiCoreDspIsMasterRecording();

  Future<void> crateApiCoreDspKaraokeCancel();

  Future<double> crateApiCoreDspKaraokeProgress();

  Future<bool> crateApiCoreDspKaraokeSeparate({
    required String inputPath,
    required String modelPath,
    required String outputPath,
  });

  Future<bool> crateApiCoreDspNormalizeLufs({required String inputPath});

  Future<BigInt> crateApiCoreDspOutroEnergyEndMs({
    required String inputPath,
    required BigInt durationMs,
  });

  Future<bool> crateApiCoreDspProcessAutoTrim({required String inputPath});

  Future<bool> crateApiCoreDspProcessFullPipeline({
    required String inputPath,
    required bool isMegamix,
  });

  Future<List<String>> crateApiCoreMetadataProcessMetadata({
    required String inputPath,
  });

  Future<String> crateApiCoreDspReadAudioGenre({required String inputPath});

  Future<MasterTags> crateApiCoreDspReadMasterTags({required String inputPath});

  Future<void> crateApiCoreDspStartMasterRecording({
    required String outputPath,
    required int bitrateKbps,
  });

  Future<void> crateApiCoreDspStopMasterRecording();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<double> crateApiCoreDspAutoDetectAndInjectBpm({
    required String inputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspAutoDetectAndInjectBpmConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspAutoDetectAndInjectBpmConstMeta =>
      const TaskConstMeta(
        debugName: "auto_detect_and_inject_bpm",
        argNames: ["inputPath"],
      );

  @override
  Future<bool> crateApiCoreDspCheckWatermark({required String inputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspCheckWatermarkConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspCheckWatermarkConstMeta =>
      const TaskConstMeta(
        debugName: "check_watermark",
        argNames: ["inputPath"],
      );

  @override
  Future<bool> crateApiCoreDspClearWatermark({required String inputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspClearWatermarkConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspClearWatermarkConstMeta =>
      const TaskConstMeta(
        debugName: "clear_watermark",
        argNames: ["inputPath"],
      );

  @override
  Future<Uint8List> crateApiCoreDspDecodeMonoPcm({
    required String inputPath,
    required int startSecs,
    required int lengthSecs,
    required int targetRate,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_u_32(startSecs, serializer);
          sse_encode_u_32(lengthSecs, serializer);
          sse_encode_u_32(targetRate, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspDecodeMonoPcmConstMeta,
        argValues: [inputPath, startSecs, lengthSecs, targetRate],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspDecodeMonoPcmConstMeta =>
      const TaskConstMeta(
        debugName: "decode_mono_pcm",
        argNames: ["inputPath", "startSecs", "lengthSecs", "targetRate"],
      );

  @override
  Future<bool> crateApiCoreDspEncodeToMp3({
    required String inputPath,
    required String outputPath,
    required int bitrateKbps,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(outputPath, serializer);
          sse_encode_u_32(bitrateKbps, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspEncodeToMp3ConstMeta,
        argValues: [inputPath, outputPath, bitrateKbps],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspEncodeToMp3ConstMeta => const TaskConstMeta(
    debugName: "encode_to_mp3",
    argNames: ["inputPath", "outputPath", "bitrateKbps"],
  );

  @override
  Future<BigInt> crateApiCoreDspExactDurationMs({required String inputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspExactDurationMsConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspExactDurationMsConstMeta =>
      const TaskConstMeta(
        debugName: "exact_duration_ms",
        argNames: ["inputPath"],
      );

  @override
  Future<BigInt> crateApiCoreDspGetAudioDurationMs({
    required String inputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspGetAudioDurationMsConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspGetAudioDurationMsConstMeta =>
      const TaskConstMeta(
        debugName: "get_audio_duration_ms",
        argNames: ["inputPath"],
      );

  @override
  Future<void> crateApiCoreDspInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreDspInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<bool> crateApiCoreDspInjectWatermark({required String inputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspInjectWatermarkConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspInjectWatermarkConstMeta =>
      const TaskConstMeta(
        debugName: "inject_watermark",
        argNames: ["inputPath"],
      );

  @override
  Future<bool> crateApiCoreDspIsMasterRecording() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreDspIsMasterRecordingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspIsMasterRecordingConstMeta =>
      const TaskConstMeta(debugName: "is_master_recording", argNames: []);

  @override
  Future<void> crateApiCoreDspKaraokeCancel() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreDspKaraokeCancelConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspKaraokeCancelConstMeta =>
      const TaskConstMeta(debugName: "karaoke_cancel", argNames: []);

  @override
  Future<double> crateApiCoreDspKaraokeProgress() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_f_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreDspKaraokeProgressConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspKaraokeProgressConstMeta =>
      const TaskConstMeta(debugName: "karaoke_progress", argNames: []);

  @override
  Future<bool> crateApiCoreDspKaraokeSeparate({
    required String inputPath,
    required String modelPath,
    required String outputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_String(modelPath, serializer);
          sse_encode_String(outputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspKaraokeSeparateConstMeta,
        argValues: [inputPath, modelPath, outputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspKaraokeSeparateConstMeta =>
      const TaskConstMeta(
        debugName: "karaoke_separate",
        argNames: ["inputPath", "modelPath", "outputPath"],
      );

  @override
  Future<bool> crateApiCoreDspNormalizeLufs({required String inputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspNormalizeLufsConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspNormalizeLufsConstMeta =>
      const TaskConstMeta(debugName: "normalize_lufs", argNames: ["inputPath"]);

  @override
  Future<BigInt> crateApiCoreDspOutroEnergyEndMs({
    required String inputPath,
    required BigInt durationMs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_u_64(durationMs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_64,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreDspOutroEnergyEndMsConstMeta,
        argValues: [inputPath, durationMs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspOutroEnergyEndMsConstMeta =>
      const TaskConstMeta(
        debugName: "outro_energy_end_ms",
        argNames: ["inputPath", "durationMs"],
      );

  @override
  Future<bool> crateApiCoreDspProcessAutoTrim({required String inputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspProcessAutoTrimConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspProcessAutoTrimConstMeta =>
      const TaskConstMeta(
        debugName: "process_auto_trim",
        argNames: ["inputPath"],
      );

  @override
  Future<bool> crateApiCoreDspProcessFullPipeline({
    required String inputPath,
    required bool isMegamix,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          sse_encode_bool(isMegamix, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspProcessFullPipelineConstMeta,
        argValues: [inputPath, isMegamix],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspProcessFullPipelineConstMeta =>
      const TaskConstMeta(
        debugName: "process_full_pipeline",
        argNames: ["inputPath", "isMegamix"],
      );

  @override
  Future<List<String>> crateApiCoreMetadataProcessMetadata({
    required String inputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreMetadataProcessMetadataConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreMetadataProcessMetadataConstMeta =>
      const TaskConstMeta(
        debugName: "process_metadata",
        argNames: ["inputPath"],
      );

  @override
  Future<String> crateApiCoreDspReadAudioGenre({required String inputPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreDspReadAudioGenreConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspReadAudioGenreConstMeta =>
      const TaskConstMeta(
        debugName: "read_audio_genre",
        argNames: ["inputPath"],
      );

  @override
  Future<MasterTags> crateApiCoreDspReadMasterTags({
    required String inputPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(inputPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_master_tags,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiCoreDspReadMasterTagsConstMeta,
        argValues: [inputPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspReadMasterTagsConstMeta =>
      const TaskConstMeta(
        debugName: "read_master_tags",
        argNames: ["inputPath"],
      );

  @override
  Future<void> crateApiCoreDspStartMasterRecording({
    required String outputPath,
    required int bitrateKbps,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outputPath, serializer);
          sse_encode_u_32(bitrateKbps, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspStartMasterRecordingConstMeta,
        argValues: [outputPath, bitrateKbps],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspStartMasterRecordingConstMeta =>
      const TaskConstMeta(
        debugName: "start_master_recording",
        argNames: ["outputPath", "bitrateKbps"],
      );

  @override
  Future<void> crateApiCoreDspStopMasterRecording() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiCoreDspStopMasterRecordingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiCoreDspStopMasterRecordingConstMeta =>
      const TaskConstMeta(debugName: "stop_master_recording", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  MasterTags dco_decode_master_tags(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return MasterTags(
      analyzed: dco_decode_bool(arr[0]),
      gainDb: dco_decode_f_64(arr[1]),
      lufs: dco_decode_f_64(arr[2]),
      peak: dco_decode_f_64(arr[3]),
      leadMs: dco_decode_u_64(arr[4]),
      tailMs: dco_decode_u_64(arr[5]),
      bpm: dco_decode_f_64(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  MasterTags sse_decode_master_tags(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_analyzed = sse_decode_bool(deserializer);
    var var_gainDb = sse_decode_f_64(deserializer);
    var var_lufs = sse_decode_f_64(deserializer);
    var var_peak = sse_decode_f_64(deserializer);
    var var_leadMs = sse_decode_u_64(deserializer);
    var var_tailMs = sse_decode_u_64(deserializer);
    var var_bpm = sse_decode_f_64(deserializer);
    return MasterTags(
      analyzed: var_analyzed,
      gainDb: var_gainDb,
      lufs: var_lufs,
      peak: var_peak,
      leadMs: var_leadMs,
      tailMs: var_tailMs,
      bpm: var_bpm,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_master_tags(MasterTags self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.analyzed, serializer);
    sse_encode_f_64(self.gainDb, serializer);
    sse_encode_f_64(self.lufs, serializer);
    sse_encode_f_64(self.peak, serializer);
    sse_encode_u_64(self.leadMs, serializer);
    sse_encode_u_64(self.tailMs, serializer);
    sse_encode_f_64(self.bpm, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
