[package]
name = "rust_lib_djstudio_player"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.12.0"
regex = "1.10.4"
symphonia = { version = "0.5.3", features = ["all"] }
id3 = "1.14.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }
