// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `atomic_replace`, `execute_ffmpeg_with_kill_switch`, `extract_bpm_dsp`, `extract_json_value`, `get_ffmpeg_path`, `spawn_headless_ffmpeg`

void abortActiveProcess() =>
    RustLib.instance.api.crateApiCoreDspAbortActiveProcess();

Future<bool> processAutoTrim({required String inputPath}) =>
    RustLib.instance.api.crateApiCoreDspProcessAutoTrim(inputPath: inputPath);

Future<bool> injectWatermark({required String inputPath}) =>
    RustLib.instance.api.crateApiCoreDspInjectWatermark(inputPath: inputPath);

Future<bool> normalizeLufs({required String inputPath}) =>
    RustLib.instance.api.crateApiCoreDspNormalizeLufs(inputPath: inputPath);

Future<bool> processFullPipeline({required String inputPath}) => RustLib
    .instance
    .api
    .crateApiCoreDspProcessFullPipeline(inputPath: inputPath);

Future<bool> checkWatermark({required String inputPath}) =>
    RustLib.instance.api.crateApiCoreDspCheckWatermark(inputPath: inputPath);

Future<bool> clearWatermark({required String inputPath}) =>
    RustLib.instance.api.crateApiCoreDspClearWatermark(inputPath: inputPath);

Future<String> readAudioGenre({required String inputPath}) =>
    RustLib.instance.api.crateApiCoreDspReadAudioGenre(inputPath: inputPath);

Future<double> autoDetectAndInjectBpm({required String inputPath}) => RustLib
    .instance
    .api
    .crateApiCoreDspAutoDetectAndInjectBpm(inputPath: inputPath);
